In [2]:
import numpy as np

a=np.array([1,2,3,4])
print(type(a))

<class 'numpy.ndarray'>


In [7]:
# a=np.arange(1,0)
# a
a=np.arange(1,4,1)
print(a)

[1 2 3]


In [31]:
a=np.array([[1,2,3],[45,50,9]],dtype='str')
print(type(a))
print(a)
a[1,-3]

<class 'numpy.ndarray'>
[['1' '2' '3']
 ['45' '50' '9']]


'45'

In [9]:
a=np.arange(1,13).reshape(4,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
# a=np.arange(1,13).reshape(4,3)
# print(a)
# print(a.shape)
# b=np.arange(1,4).reshape(-1,3)
# print(b)
# print(b.shape)
# d=np.concatenate((a,b),axis=0)
# print(d)
# print(d.shape)
# e=d[0].shape+a.shape
# print(e)


# a=np.array(5)
# print(a)
# b=np.array([5,7,8])
# print(b)
# print(b+a)


# a=np.arange(1,5).reshape(2,2)
# b=np.arange(1,3).reshape(-1,2)
# print(a+b)

# a=np.arange(1,5).reshape(2,2)
# b=np.arange(1,3).reshape(2,-1)
# print(a+b)

a=np.arange(1,9).reshape(4,2)
b=np.arange(1,5).reshape(-1,2)
print(a+b)




ValueError: operands could not be broadcast together with shapes (4,2) (2,2) 

In [11]:
a=np.arange(1,13).reshape(2,3,2,1)
a

array([[[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]]],


       [[[ 7],
         [ 8]],

        [[ 9],
         [10]],

        [[11],
         [12]]]])

In [30]:
# a=np.array([1,2,3,4]).reshape(2,2)
a=np.array((1,2,3,4)).reshape(2,2)
print(a)
a[1,-2]

[[1 2]
 [3 4]]


3

In [19]:
a=np.random.random((2,2))
a

array([[0.79256058, 0.88742389],
       [0.14487625, 0.6955687 ]])

In [28]:
a=np.random.randint(2,10)
a

5

In [24]:
a=np.ones([3,4])
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
a=np.zeros([3,4])
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
a=np.identity(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
a=np.linspace(4,5,9)
a

array([4.   , 4.125, 4.25 , 4.375, 4.5  , 4.625, 4.75 , 4.875, 5.   ])

In [35]:
a=np.linspace(-100,100,10,dtype=int)
a

array([-100,  -78,  -56,  -34,  -12,   11,   33,   55,   77,  100])

In [63]:
a=np.arange(1,13)
b=np.arange(1,13).reshape(4,3)
c=np.arange(1,13).reshape(2,2,3)
print(a)
print(b)
print(c)
print(a.ndim)
print(b.shape)
print(a.size)
print(a.dtype)
print(b[0].shape[0]+c[0].shape[0])
print(b[0].shape[0]+c[1].shape[1])
print(a[a%2!=0])
print(a[[7,8,9]])
print(b[1,2])
print(b[-2,-2])


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
(4, 3)
12
int32
5
6
[ 1  3  5  7  9 11]
[ 8  9 10]
6
8


array([[1, 2, 3],
       [7, 8, 9]])

In [17]:
# b=np.arange(1,13).reshape(3,4)
# print(b)
# c = np.array([b[0][0], b[0][b.shape[1]-1], b[2][0], b[2][b.shape[1]-1]]).reshape(2, 2)
# print(c)
# b[::-1,::-1]
d=np.arange(1,13).reshape(2,2,3)
print(d)
print(d[:,0,:])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [7 8 9]]


In [58]:
a=np.random.randint(1,100,size=(3,4))
# print(a)
# print(np.min(a,axis=0))
# print(np.min(a,axis=1))
# max=a[1][0]
# for i in a[1]:
#     if i>max:
#         max=i
# print(max)
print(a)
print(np.sort(a,axis=0))
print(np.sort(a,axis=1))

[[57 91 81 22]
 [18 71 86 94]
 [59  1 60  2]]
[[18  1 60  2]
 [57 71 81 22]
 [59 91 86 94]]
[[22 57 81 91]
 [18 71 86 94]
 [ 1  2 59 60]]


In [76]:
print(a)
# b=list(a)
# b.sort(key=lambda x:x[-1])
# d=np.array(b)
# print(d)
print(a[:,-2])
a[np.argsort(a[:,-2])]


[[57 91 81 22]
 [18 71 86 94]
 [59  1 60  2]]
[81 86 60]


array([[59,  1, 60,  2],
       [57, 91, 81, 22],
       [18, 71, 86, 94]])

In [13]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(1,4).reshape(3,1)
x=np.arange(1,10).reshape(3,3)
y=np.arange(1,4).reshape(1,3)
d = np.concatenate((a, b), axis=1)
e=np.concatenate((x,y),axis=0)
print(a)
print()
print(b)
print()
print(x)
print()
print(y)
print()
print(d)
print()
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1]
 [2]
 [3]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]]

[[1 2 3 1]
 [4 5 6 2]
 [7 8 9 3]]

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]


In [77]:
64+54+73+74+48

313

In [10]:
a=np.random.randint(1,13,size=(3,4))
print(a)
np.where(a>5,1,0)

[[10  5  3  3]
 [11 11  1 10]
 [10  3  4  4]]


array([[1, 0, 0, 0],
       [1, 1, 0, 1],
       [1, 0, 0, 0]])

In [15]:
np.where(a>2,1,np.where(a>5,2,0))


array([[0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [25]:
np.arange(6).reshape(3,-1)

ValueError: cannot reshape array of size 13 into shape (3,newaxis)

In [26]:
class A:
    m=5000
    def __init__(self):
        self.m+=A.m
        
class b(A):
    m=1000
    def display(self):
        self.m+=2000
        print(self.m)
o=b()
o.display()

8000


In [27]:
class A:
    a=20
    def __init__(self):
        self.a+=10
        
class b(A):
    a=15
    def buy(self):
        pass
class C(b,A):
    a=30
    def buy(self):
        print(self.a)
o=C()
o.buy()

40


In [9]:
a=np.arange(1,13)
print(a)
print(np.array_split(a,3))
print(np.array_split(a,7))
print(np.array_split(a,15))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10]), array([11]), array([12])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8]), array([9]), array([10]), array([11]), array([12]), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32)]


In [19]:
a=np.arange(1,13).reshape(3,4)
print(a)
print(np.array_split(a,3,axis=1))
print(np.array_split(a,2,axis=0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3],
       [ 7],
       [11]]), array([[ 4],
       [ 8],
       [12]])]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]


In [38]:
class Matrix:
    def __init__(self,arr):
        self.arr=arr
    def __add__(self,other):
        return self.arr+other.arr
    def __sub__(self,other):
        return self.arr+other.arr
    def __mul__(self,other):
        return np.dot(self.arr,other.arr)
    def transpose(self):
        return self.arr.T
    
a=np.arange(1,13).reshape(3,4)
b=np.arange(5,17).reshape(3,4)
x=np.arange(1,13).reshape(3,4)
y=np.arange(5,17).reshape(4,3)
print(a)
print(b)
obj1=Matrix(a)
obj2=Matrix(b)
obj3=Matrix(x)
obj4=Matrix(y)
print("add(a,b):")
print(obj1+obj2)
print("sub(a,b):")
print(obj1-obj2)
print("mul(x,y):")
print(obj3*obj4)
print("transpose(a):")
print(obj1.transpose())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
add(a,b):
[[ 6  8 10 12]
 [14 16 18 20]
 [22 24 26 28]]
sub(a,b):
[[ 6  8 10 12]
 [14 16 18 20]
 [22 24 26 28]]
mul(x,y):
[[110 120 130]
 [262 288 314]
 [414 456 498]]
transpose(a):
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
