In [2]:
import numpy as np

a=np.array([1,2,3,4])
print(type(a))

<class 'numpy.ndarray'>


In [7]:
# a=np.arange(1,0)
# a
a=np.arange(1,4,1)
print(a)

[1 2 3]


In [6]:
a=np.array([[1,2,3],[45,50,9]],dtype='str')
print(type(a))
a

<class 'numpy.ndarray'>


array([['1', '2', '3'],
       ['45', '50', '9']], dtype='<U2')

In [9]:
a=np.arange(1,13).reshape(4,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
a=np.arange(1,13).reshape(2,3,2,1)
a

array([[[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]]],


       [[[ 7],
         [ 8]],

        [[ 9],
         [10]],

        [[11],
         [12]]]])

In [17]:
# a=np.array([1,2,3,4]).reshape(2,2)
a=np.array((1,2,3,4)).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [19]:
a=np.random.random((2,2))
a

array([[0.79256058, 0.88742389],
       [0.14487625, 0.6955687 ]])

In [28]:
a=np.random.randint(2,10)
a

5

In [24]:
a=np.ones([3,4])
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
a=np.zeros([3,4])
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
a=np.identity(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
a=np.linspace(4,5,9)
a

array([4.   , 4.125, 4.25 , 4.375, 4.5  , 4.625, 4.75 , 4.875, 5.   ])

In [35]:
a=np.linspace(-100,100,10,dtype=int)
a

array([-100,  -78,  -56,  -34,  -12,   11,   33,   55,   77,  100])

In [63]:
a=np.arange(1,13)
b=np.arange(1,13).reshape(4,3)
c=np.arange(1,13).reshape(2,2,3)
print(a)
print(b)
print(c)
print(a.ndim)
print(b.shape)
print(a.size)
print(a.dtype)
print(b[0].shape[0]+c[0].shape[0])
print(b[0].shape[0]+c[1].shape[1])
print(a[a%2!=0])
print(a[[7,8,9]])
print(b[1,2])
print(b[-2,-2])


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
(4, 3)
12
int32
5
6
[ 1  3  5  7  9 11]
[ 8  9 10]
6
8


array([[1, 2, 3],
       [7, 8, 9]])

In [67]:
# b=np.arange(1,13).reshape(3,4)
# print(b)
# c = np.array([b[0][0], b[0][b.shape[1]-1], b[2][0], b[2][b.shape[1]-1]]).reshape(2, 2)
# print(c)
# b[::-1,::-1]
d=np.arange(1,13).reshape(2,2,3)
print(d)
print(d[:,0,:])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [7 8 9]]


In [76]:
a=np.random.randint(1,100,size=(3,4))
# print(a)
# print(np.min(a,axis=0))
# print(np.min(a,axis=1))
# max=a[1][0]
# for i in a[1]:
#     if i>max:
#         max=i
# print(max)
print(a)
print(np.sort(a,axis=0))
print(np.sort(a,axis=1))

[[54 80 31 54]
 [81  5 92 17]
 [26 90 99 52]]
[[26  5 31 17]
 [54 80 92 52]
 [81 90 99 54]]
[[31 54 54 80]
 [ 5 17 81 92]
 [26 52 90 99]]


In [91]:
print(a)
b=list(a)
b.sort(key=lambda x:x[-1])
d=np.array(b)
print(d)
d[np.argsort(d[:,-1])]

[[54 80 31 54]
 [81  5 92 17]
 [26 90 99 52]]
[[81  5 92 17]
 [26 90 99 52]
 [54 80 31 54]]


array([[81,  5, 92, 17],
       [26, 90, 99, 52],
       [54, 80, 31, 54]])

In [93]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(1,4).reshape(3,1)
d=np.concatenate((a,b),axis=0)
e=np.concatenate((a,b),axis=1)
print(a)
print(b)
print(d)
print(e)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 1