In [2]:
import numpy as np

a=np.array([1,2,3,4])
print(type(a))

<class 'numpy.ndarray'>


In [10]:
a=np.arange(1,0)
a
a=np.arange(1,4,-1)
a

array([], dtype=int32)

In [6]:
a=np.array([[1,2,3],[45,50,9]],dtype='str')
print(type(a))
a

<class 'numpy.ndarray'>


array([['1', '2', '3'],
       ['45', '50', '9']], dtype='<U2')

In [9]:
a=np.arange(1,13).reshape(4,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
a=np.arange(1,13).reshape(2,3,2,1)
a

array([[[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]]],


       [[[ 7],
         [ 8]],

        [[ 9],
         [10]],

        [[11],
         [12]]]])

In [17]:
# a=np.array([1,2,3,4]).reshape(2,2)
a=np.array((1,2,3,4)).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [19]:
a=np.random.random((2,2))
a

array([[0.79256058, 0.88742389],
       [0.14487625, 0.6955687 ]])

In [28]:
a=np.random.randint(2,10)
a

5

In [24]:
a=np.ones([3,4])
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
a=np.zeros([3,4])
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
a=np.identity(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
a=np.linspace(4,5,9)
a

array([4.   , 4.125, 4.25 , 4.375, 4.5  , 4.625, 4.75 , 4.875, 5.   ])

In [35]:
a=np.linspace(-100,100,10,dtype=int)
a

array([-100,  -78,  -56,  -34,  -12,   11,   33,   55,   77,  100])